name: build-and-deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'years/**'
      - '.github/workflows/deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install jupyter-book toolchain
        run: |
          pip install -U \
            "jupyter-book>=1.0,<1.1" \
            "sphinx==7.3.7" \
            "docutils==0.20.1" \
            "myst-nb>=1.1.0" \
            "sphinx-external-toc>=1.0.0" \
            "sphinx-copybutton>=0.5.2" \
            "sphinx-design>=0.6.0" \
            "sphinxcontrib-bibtex>=2.6.0"

      # --- 2024-25 ---
      - name: Build 2024-25
        run: |
          jupyter-book build years/2024-25

      - name: Deploy 2024-25 to gh-pages/2024-25
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: years/2024-25/_build/html
          destination_dir: 2024-25
          keep_files: true

      # --- 2025-26 ---
      - name: Build 2025-26
        run: |
          jupyter-book build years/2025-26

      - name: Deploy 2025-26 to gh-pages/2025-26
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: years/2025-26/_build/html
          destination_dir: 2025-26
          keep_files: true

      # --- Root index.html ---
      - name: Create root index.html
        run: |
          mkdir _root
          cat > _root/index.html <<'EOF'
          <!doctype html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=/statistical-and-mathematical-methods/2025-26/">
          <title>Redirecting…</title>
          <h1>Statistical and Mathematical Methods — Course Site</h1>
          <p>Redirecting to the latest year:
            <a href="/statistical-and-mathematical-methods/2025-26/">2025-26</a>
          </p>
          <h2>Available years</h2>
          <ul>
            <li><a href="/statistical-and-mathematical-methods/2024-25/">2024-25</a></li>
            <li><a href="/statistical-and-mathematical-methods/2025-26/">2025-26</a></li>
          </ul>
          EOF

      - name: Deploy root index.html
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _root
          destination_dir: .
          keep_files: true
